[package]

version = "0.1.0"

category = "isaaclab"
readme  = "README.md"

title = "Go2-W Locomotion"
author = "Isaac Lab Project Developers"
maintainer = "Isaac Lab Project Developers"
description = "Wheeled quadruped locomotion environment for the Unitree Go2-W"
repository = "https://github.com/suyourice/go2w.git"
keywords = ["locomotion", "wheeled quadruped", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}

[[python.module]]
name = "go2w"
